version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432' # Expose PostgreSQL to host
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sourav
      POSTGRES_DB: souravdb # default DB
    volumes:
      - sourav-nest-postgrey:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - '8081:80' # Web UI for PostgreSQL
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sourav.com
      PGADMIN_DEFAULT_PASSWORD: sourav
    depends_on:
      - postgres

volumes:
  sourav-nest-postgrey:
